// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4PIdeDruVvWnaQiTvtmNovtfqI7jICNo',
    appId: '1:128317419490:web:7be36fb80661cdc95393bb',
    messagingSenderId: '128317419490',
    projectId: 'studysmart-5da53',
    authDomain: 'studysmart-5da53.firebaseapp.com',
    storageBucket: 'studysmart-5da53.firebasestorage.app',
    measurementId: 'G-ERJES403GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACN91HTwtu4IutO2FLNG7-IykHYW3wNQ0',
    appId: '1:128317419490:android:b3eb63a935ca4aed5393bb',
    messagingSenderId: '128317419490',
    projectId: 'studysmart-5da53',
    storageBucket: 'studysmart-5da53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPrWQ51zY7JbpZ0EL_BX_RapycW1FPpY',
    appId: '1:128317419490:ios:216b40ce10e03f705393bb',
    messagingSenderId: '128317419490',
    projectId: 'studysmart-5da53',
    storageBucket: 'studysmart-5da53.firebasestorage.app',
    iosClientId: '128317419490-hd6t669ku0oefk84gsi6j361dsj1pfin.apps.googleusercontent.com',
    iosBundleId: 'com.example.studySmartQc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwPrWQ51zY7JbpZ0EL_BX_RapycW1FPpY',
    appId: '1:128317419490:ios:216b40ce10e03f705393bb',
    messagingSenderId: '128317419490',
    projectId: 'studysmart-5da53',
    storageBucket: 'studysmart-5da53.firebasestorage.app',
    iosClientId: '128317419490-hd6t669ku0oefk84gsi6j361dsj1pfin.apps.googleusercontent.com',
    iosBundleId: 'com.example.studySmartQc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4PIdeDruVvWnaQiTvtmNovtfqI7jICNo',
    appId: '1:128317419490:web:c5192c1718a8d4065393bb',
    messagingSenderId: '128317419490',
    projectId: 'studysmart-5da53',
    authDomain: 'studysmart-5da53.firebaseapp.com',
    storageBucket: 'studysmart-5da53.firebasestorage.app',
    measurementId: 'G-03K1527Q47',
  );
}
